### ISSUE TITLE
Kubernetes CustomResourceDefinition Moving out of Beta

### ISSUE THREAD

**Issue by 5had3z** [pytorch/elastic#157]
## 🐛 Bug

apiextensions.k8s.io/v1beta1 has been depricated in favour of GA release and elastic.pytorch.org_elasticjobs.yaml no longer conforms to the new spec.

https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22

Component (check all that applies):
 * [ ] `state api`
 * [ ] `train_step api`
 * [ ] `train_loop`
 * [ ] `rendezvous`
 * [ ] `checkpoint`
 * [ ] `rollback`
 * [ ] `metrics`
 * [ ] `petctl`
 * [x] `examples`
 * [ ] `docker`
 * [x] other
 

## To Reproduce

1. Install Kubernetes 1.22 (following https://docs.nvidia.com/datacenter/cloud-native/kubernetes/install-k8s.html#step-0-before-you-begin)
2. clone this repo and follow its instructions (including kubectl apply -k config/default)

```
kubectl apply -k config/default
namespace/elastic-job unchanged
role.rbac.authorization.k8s.io/leader-election-role unchanged
clusterrole.rbac.authorization.k8s.io/elastic-job-k8s-controller-role configured
rolebinding.rbac.authorization.k8s.io/leader-election-rolebinding unchanged
clusterrolebinding.rbac.authorization.k8s.io/elastic-job-k8s-controller-rolebinding unchanged
deployment.apps/elastic-job-k8s-controller unchanged
error: unable to recognize "config/default": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
```

## Expected behavior

```
namespace/elastic-job created
customresourcedefinition.apiextensions.k8s.io/elasticjobs.elastic.pytorch.org created
role.rbac.authorization.k8s.io/leader-election-role created
clusterrole.rbac.authorization.k8s.io/manager-role created
rolebinding.rbac.authorization.k8s.io/leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/elastic-job-k8s-controller-rolebinding created
deployment.apps/elastic-job-k8s-controller create
```

## Environment

 - torchelastic version (e.g. 0.1.0rc1): stable 
 - OS (e.g., Linux): Ubuntu 20.04 Server
 - How you installed torchelastic (`conda`, `pip`, source, `docker`): source
 - Docker image and tag (if using docker): nvcr.io/nvidia/pytorch:21.07-py3
 - Build command you used (if compiling from source): kubectl apply -k config/default
 - Git commit (if installed from source): 0293cea1bc8afe4ebccce05bcf21f5509880f82a
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Execution environment (on-prem, aws, etc): on-prem
 - Any other relevant information:

## Additional context

I've literally just started to try making my own training cluster, so I'm an absolute kubernetes novice. I'm adjusting things now to try to get it to work, I'll report back if changes are successful and I can get a job running.

**Comment by kiukchung** [comment]
Thanks reporting! As of torch-1.9.0 the torchelastic-core has been upstreamed to `torch.distributed.elastic` and "extensions" such as this Kubernetes CRD is now being actively worked on from pytorch/torchx. Since you are just getting started building out your infra I believe TorchX will be a better fit for your particular usecase.

Check out these pages:
1. Quickstart guide: https://pytorch.org/torchx/master/quickstart.html.
2. Kubernetes support: https://pytorch.org/torchx/master/schedulers/kubernetes.html

Feel free to drop me an issue in the torchx github repo if you encounter issues getting a pytorch trainer running on kubernetes with torchx. Thanks!

**Comment by 5had3z** [comment]
Hi Kiuk,

It seems that volcano also might have issues with the latest version of kubernetes as well, I guess it maybe best for me to rollback?

Running the standard install from them results in the pod configuration below:
```
kubectl apply -f https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml
kubectl get pods -n volcano-system
NAME                                   READY   STATUS             RESTARTS        AGE
volcano-admission-f5f4fb5b6-wh99g      0/1     CrashLoopBackOff   21 (110s ago)   84m
volcano-admission-init--1-j4fnt        0/1     Completed          0               84m
volcano-controllers-5bbcc9c49f-njgwf   1/1     Running            0               84m
volcano-scheduler-5665cdc4d9-nz822     1/1     Running            0               84m
```

With the description and logs of the pod:
```
kubectl describe pod volcano-admission-f5f4fb5b6-wh99g -n volcano-system

Name:         volcano-admission-f5f4fb5b6-wh99g
Namespace:    volcano-system
Priority:     0
Node:         mu00186365/130.194.132.210
Start Time:   Sat, 07 Aug 2021 02:52:37 +0000
Labels:       app=volcano-admission
              pod-template-hash=f5f4fb5b6
Annotations:  cni.projectcalico.org/containerID: 1adc3c86ddfb599f62cb52bcb1e27192c764a6d372192c6df0607e244dc6b92f
              cni.projectcalico.org/podIP: 192.168.161.80/32
              cni.projectcalico.org/podIPs: 192.168.161.80/32
Status:       Running
IP:           192.168.161.80
IPs:
  IP:           192.168.161.80
Controlled By:  ReplicaSet/volcano-admission-f5f4fb5b6
Containers:
  admission:
    Container ID:  containerd://8c84bf6ed17af068162a84453796fe0f72c1dbd7291e49926bd09b6bfe19f9a2
    Image:         volcanosh/vc-webhook-manager:latest
    Image ID:      docker.io/volcanosh/vc-webhook-manager@sha256:54491b8354620f5b0e006bd68b59ccd5cb50e1d0b985bd8bbe4542d4f51cc468
    Port:          <none>
    Host Port:     <none>
    Args:
      --tls-cert-file=/admission.local.config/certificates/tls.crt
      --tls-private-key-file=/admission.local.config/certificates/tls.key
      --ca-cert-file=/admission.local.config/certificates/ca.crt
      --admission-conf=/admission.local.config/configmap/volcano-admission.conf
      --webhook-namespace=volcano-system
      --webhook-service-name=volcano-admission-service
      --logtostderr
      --port=8443
      -v=4
      2>&1
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Sat, 07 Aug 2021 04:10:11 +0000
      Finished:     Sat, 07 Aug 2021 04:10:11 +0000
    Ready:          False
    Restart Count:  20
    Environment:    <none>
    Mounts:
      /admission.local.config/certificates from admission-certs (ro)
      /admission.local.config/configmap from admission-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-w9nq4 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  admission-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  volcano-admission-secret
    Optional:    false
  admission-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      volcano-admission-configmap
    Optional:  false
  kube-api-access-w9nq4:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason   Age                    From     Message
  ----     ------   ----                   ----     -------
  Warning  BackOff  3m35s (x345 over 78m)  kubelet  Back-off restarting failed container
```
```
kubectl logs volcano-admission-f5f4fb5b6-wh99g -n volcano-system
unknown flag: --admission-conf
Usage of /vc-webhook-manager:
      --add-dir-header                   If true, adds the file directory to the header
      --alsologtostderr                  log to standard error as well as files
      --ca-cert-file string              File containing the x509 Certificate for HTTPS.
      --kube-api-burst int               Burst to use while talking with kubernetes apiserver (default 100)
      --kube-api-qps float32             QPS to use while talking with kubernetes apiserver (default 50)
      --kubeconfig string                Path to kubeconfig file with authorization and master location information.
      --log-backtrace-at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log-dir string                   If non-empty, write log files in this directory
      --log-file string                  If non-empty, use this log file
      --log-file-max-size uint           Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
      --log-flush-frequency duration     Maximum number of seconds between log flushes (default 5s)
      --logtostderr                      log to standard error instead of files (default true)
      --master string                    The address of the Kubernetes API server (overrides any value in kubeconfig)
      --port int                         the port used by admission-controller-server. (default 8443)
      --scheduler-name string            Volcano will handle pods whose .spec.SchedulerName is same as scheduler-name (default "volcano")
      --skip-headers                     If true, avoid header prefixes in the log messages
      --skip-log-headers                 If true, avoid headers when opening log files
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
      --tls-cert-file string             File containing the default x509 Certificate for HTTPS. (CA cert, if any, concatenated after server cert).
      --tls-private-key-file string      File containing the default x509 private key matching --tls-cert-file.
  -v, --v Level                          number for the log level verbosity
      --version                          Show version and quit
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging
      --webhook-namespace string         The namespace of this webhook
      --webhook-service-name string      The name of this webhook
      --webhook-url string               The url of this webhook
unknown flag: --admission-conf
```

So when I try running the torchX 'hello world' after installing with the command below I get the following result. Also typo in the kubernetes example documentation which has --scheduler_opts instead of --scheduler_args (torchx/schedulers/kubernetes_scheduler:ln245).

```
sudo python3 -m pip install -e .
torchx run --scheduler kubernetes --scheduler_args namespace=default,queue=test utils.echo --msg hello
kubernetes://torchx_monash/default:echo-52cnp
=== RUN RESULT ===
Launched app: kubernetes://torchx_monash/default:echo-52cnp
Traceback (most recent call last):
  File "/usr/local/bin/torchx", line 33, in <module>
    sys.exit(load_entry_point('torchx', 'console_scripts', 'torchx')())
  File "/home/monash/torchx/torchx/cli/main.py", line 62, in main
    args.func(args)
  File "/home/monash/torchx/torchx/cli/cmd_run.py", line 120, in run
    status = runner.status(app_handle)
  File "/home/monash/torchx/torchx/runner/api.py", line 294, in status
    desc = scheduler.describe(app_id)
  File "/home/monash/torchx/torchx/schedulers/kubernetes_scheduler.py", line 342, in describe
    status = resp["status"]
KeyError: 'status'
```

**Comment by 5had3z** [comment]
Volcano works if I use v1.3.0 yaml config instead of master, but the key error still exists with TorchX, should I raise the issue over there?

```
kubectl get services -n volcano-systemNAME                        TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
volcano-admission-service   ClusterIP   10.107.36.106   <none>        443/TCP    8m4s
volcano-scheduler-service   ClusterIP   10.98.139.178   <none>        8080/TCP   8m3s
```
```
kubectl get pods -n volcano-system
NAME                                   READY   STATUS      RESTARTS   AGE
volcano-admission-5bb77cd5b7-bwxqd     1/1     Running     0          8m16s
volcano-admission-init--1-9sj2x        0/1     Completed   0          8m16s
volcano-controllers-5bbcc9c49f-5prtw   1/1     Running     0          8m16s
volcano-scheduler-5665cdc4d9-s6frp     1/1     Running     0          8m15s
```
```
kubectl get jobs -n volcano-system
NAME                     COMPLETIONS   DURATION   AGE
volcano-admission-init   1/1           3s         9m9s
```
```
kubectl get deployments -n volcano-system
NAME                  READY   UP-TO-DATE   AVAILABLE   AGE
volcano-admission     1/1     1            1           9m37s
volcano-controllers   1/1     1            1           9m37s
volcano-scheduler     1/1     1            1           9m36s
```

**Comment by kiukchung** [comment]
thanks for trying torchx out. Yes please do file an issue in torchx github with this bug report and we’ll take a look at what’s going on and have a fix for you promptly.
