### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices

### ISSUE THREAD

**Issue by aitrics-chris** [pytorch/elastic#169]
## 🐛 Bug

Component (check all that applies):
 * [ ] `state api`
 * [ ] `train_step api`
 * [ ] `train_loop`
 * [ ] `rendezvous`
 * [ ] `checkpoint`
 * [ ] `rollback`
 * [ ] `metrics`
 * [ ] `petctl`
 * [ ] `examples`
 * [ ] `docker`
 * [x] other
 

## To Reproduce

1. download ``` https://github.com/pytorch/elastic/blob/master/examples/imagenet/main.py ```
2. Change the ImageNet dataset to CIFAR-10 dataset [[LINK](https://drive.google.com/file/d/1Un8OOJG82AE413RLoGjvgXerMHC4LdMe/view?usp=sharing)]
3. Change the filename from main.py to main_launch.py
4. ```torchrun --standalone --nnodes=1 --nproc_per_node=8 main_launch.py```

```
Traceback (most recent call last):
  File "main_launch.py", line 605, in <module>
    main()
  File "main_launch.py", line 198, in main
    is_best = acc1 > state.best_acc1
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:6 and cuda:0!
 * Acc@1 67.580 Acc@5 96.950
Traceback (most recent call last):
  File "main_launch.py", line 605, in <module>
    main()
  File "main_launch.py", line 198, in main
    is_best = acc1 > state.best_acc1
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!
 * Acc@1 67.580 Acc@5 96.950
 * Acc@1 67.580 Acc@5 96.950
Traceback (most recent call last):
  File "main_launch.py", line 605, in <module>
    main()
  File "main_launch.py", line 198, in main
    is_best = acc1 > state.best_acc1
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:3 and cuda:0!
Traceback (most recent call last):
  File "main_launch.py", line 605, in <module>
    main()
  File "main_launch.py", line 198, in main
    is_best = acc1 > state.best_acc1
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:4 and cuda:0!
=> saved checkpoint for epoch 9 at /tmp/checkpoint.pth.tar
=> best model found at epoch 9 saving to /tmp/model_best.pth.tar
 * Acc@1 67.580 Acc@5 96.950
Traceback (most recent call last):
  File "main_launch.py", line 605, in <module>
    main()
  File "main_launch.py", line 198, in main
    is_best = acc1 > state.best_acc1
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:2 and cuda:0!
 * Acc@1 67.580 Acc@5 96.950
 * Acc@1 67.580 Acc@5 96.950
Traceback (most recent call last):
  File "main_launch.py", line 605, in <module>
    main()
  File "main_launch.py", line 198, in main
    is_best = acc1 > state.best_acc1
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:7 and cuda:0!
Traceback (most recent call last):
  File "main_launch.py", line 605, in <module>
    main()
  File "main_launch.py", line 198, in main
    is_best = acc1 > state.best_acc1
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:5 and cuda:0!
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 12197 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 12198) of binary: /home/chris/anaconda3/envs/plts/bin/python
Traceback (most recent call last):
  File "/home/chris/anaconda3/envs/plts/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.12.0', 'console_scripts', 'torchrun')())
  File "/home/chris/anaconda3/envs/plts/lib/python3.7/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/chris/anaconda3/envs/plts/lib/python3.7/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/home/chris/anaconda3/envs/plts/lib/python3.7/site-packages/torch/distributed/run.py", line 755, in run
    )(*cmd_args)
  File "/home/chris/anaconda3/envs/plts/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/chris/anaconda3/envs/plts/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
```

## Environment

 - torchelastic version: 0.2.0
 - OS (e.g., Linux): Ubuntu 18.04.4 LTS 
 - How you installed torchelastic (`conda`, `pip`, source, `docker`): pip
 - Docker image and tag (if using docker): docker is ***NOT*** used
 - Build command you used (if compiling from source):
 - Git commit (if installed from source):
 - Python version: 3.7.13
 - CUDA/cuDNN version: CUDA 10.2
 - GPU models and configuration: TITAN V *8
 - Execution environment (on-prem, aws, etc):
On Terminal, using the command at below (I changed the file name from main.py to main_launch.py):
 ```
torchrun --standalone --nnodes=1 --nproc_per_node=8 main_launch.py
```

 - Any other relevant information:

I replaced the ImageNet dataset with CIFAR-10 dataset. Other than this, I did not change the code from:
```
https://github.com/pytorch/elastic/blob/master/examples/imagenet/main.py
```

**Comment by kiukchung** [comment]
Thanks for reporting. Which version of pytorch are you using?

**Comment by aitrics-chris** [comment]
Thank you for the response @kiukchung 

PyTorch: 1.12.0
CUDA: 10.2
CUDNN: 7.6.5

I installed via:
```
conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
```

Thank you.

**Comment by kiukchung** [comment]
Got it, I think the fix is to change this block: https://github.com/pytorch/elastic/blob/master/examples/imagenet/main.py#L384-L387 to 

```
        if rank != max_rank:
            with io.BytesIO(blob.numpy()) as f:
                state.load(f, device_id)

```

e.g. just call `state.load(f, device_id)` instead of calling `torch.load(f)` (which is problematic since this will load the tensors in `f` onto the same device they were stored when they were snapshotted) then `state.apply_snapshot(snapshot, device_id)` (which then loads the tensors onto the correct device - effectively you now have 2 copies, one on each device).

If this works feel free to put up a PR and I'll approve it.

**Comment by aitrics-chris** [comment]
Error solved. Thank you :)
