### ISSUE TITLE
Imagenet example crashing on Kubernetes

### ISSUE THREAD

**Issue by chauhang** [pytorch/elastic#90]
## 🐛 Bug

The Imagenet example does not work on Kubernetes, crashes with error " ValueError: Start index 100000 should be less than dataset size 100000"

Component (check all that applies):
 * [ ] `state api`
 * [ ] `train_step api`
 * [ ] `train_loop`
 * [ ] `rendezvous`
 * [ ] `checkpoint`
 * [ ] `rollback`
 * [ ] `metrics`
 * [ ] `petctl`
 * [X] `examples`
 * [ ] `docker`
 * [ ] other
 

## To Reproduce

1. Follow the steps as per the K8s docs to configure EKS/K8s cluster and get the imagenet example working on it
1. See the logs for the imagenet example, it crashes after sometime, see details for error below: 

## Error logs: 
```
kubectl logs -f imagenet-worker-0  -n elastic-job

[INFO] 2020-04-07 20:09:52,429 main: epoch: 0, iteration: 1557, data_idx: 149248
[INFO] 2020-04-07 20:09:53,930 main: epoch: 0, iteration: 1558, data_idx: 149344
[INFO] 2020-04-07 20:09:55,541 main: epoch: 0, iteration: 1559, data_idx: 149440
[INFO] 2020-04-07 20:09:57,083 main: epoch: 0, iteration: 1560, data_idx: 149536
[INFO] 2020-04-07 20:09:58,689 main: epoch: 0, iteration: 1561, data_idx: 149632
[INFO] 2020-04-07 20:10:00,381 main: epoch: 0, iteration: 1562, data_idx: 149728
[INFO] 2020-04-07 20:10:01,914 main: epoch: 0, iteration: 1563, data_idx: 149824
[INFO] 2020-04-07 20:10:03,498 main: epoch: 0, iteration: 1564, data_idx: 149920
[INFO] 2020-04-07 20:10:04,813 main: epoch: 0, iteration: 1565, data_idx: 150016
[ERROR] 2020-04-07 20:10:04,864 coordinator_p2p: Rank: 1
Error: Start index 100000 should be less than dataset size 100000
ErrorType: <class 'ValueError'>
StackTrace: Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torchelastic/utils/data/cycling_iterator.py", line 36, in __next__
    return next(self._iter)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    index = self._next_index()  # may raise StopIteration
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 318, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torchelastic/train_loop.py", line 96, in train
    state, worker_stats = train_step(state)
  File "/workspace/examples/imagenet/main.py", line 285, in train_step
    input, target = next(state.data_iter)
  File "/opt/conda/lib/python3.6/site-packages/torchelastic/utils/data/cycling_iterator.py", line 40, in __next__
    self._iter = self._generator_fn(self._epoch)
  File "/workspace/examples/imagenet/main.py", line 177, in _data_iter_generator_fn
    start_index=self.data_start_index,
  File "/opt/conda/lib/python3.6/site-packages/torchelastic/utils/data/elastic_distributed_sampler.py", line 41, in __init__
    start_index, len(dataset)
ValueError: Start index 100000 should be less than dataset size 100000

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torchelastic/utils/data/cycling_iterator.py", line 36, in __next__
    return next(self._iter)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    index = self._next_index()  # may raise StopIteration
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 318, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/examples/imagenet/main.py", line 429, in <module>
    main()
  File "/workspace/examples/imagenet/main.py", line 410, in main
    args.input_path,
  File "/workspace/examples/imagenet/main.py", line 276, in single_trainer
    torchelastic.train(coordinator, train_step, state)
  File "/opt/conda/lib/python3.6/site-packages/torchelastic/train_loop.py", line 96, in train
    state, worker_stats = train_step(state)
  File "/workspace/examples/imagenet/main.py", line 285, in train_step
    input, target = next(state.data_iter)
  File "/opt/conda/lib/python3.6/site-packages/torchelastic/utils/data/cycling_iterator.py", line 40, in __next__
    self._iter = self._generator_fn(self._epoch)
  File "/workspace/examples/imagenet/main.py", line 177, in _data_iter_generator_fn
    start_index=self.data_start_index,
  File "/opt/conda/lib/python3.6/site-packages/torchelastic/utils/data/elastic_distributed_sampler.py", line 41, in __init__
    start_index, len(dataset)
ValueError: Start index 100000 should be less than dataset size 100000
```

## Expected behavior

Training job should complete without any errors

**Comment by kiukchung** [comment]
We are transitioning from 0.1.0 to 0.2.0 the kubernetes examples will be updated accordingly

**Comment by Jeffwan** [comment]
@chauhang Check here https://github.com/pytorch/elastic/issues/26

I think this is kubernetes unrelated, more on the framework side itself.

**Comment by kiukchung** [comment]
we have a new imagenet example with v0.2.0 feel free to reopen if the issue persists.
